-- MySQL Script generated by MySQL Workbench
-- Wed Jun  6 13:53:48 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema knowledgehub
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema knowledgehub
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `knowledgehub` DEFAULT CHARACTER SET utf8 ;
USE `knowledgehub` ;

-- -----------------------------------------------------
-- Table `knowledgehub`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knowledgehub`.`role` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `role_name` VARCHAR(45) NOT NULL,
  `role_value` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `knowledgehub`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knowledgehub`.`status` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `status_name` VARCHAR(45) NOT NULL,
  `status_value` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `knowledgehub`.`user_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knowledgehub`.`user_type` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_type_name` VARCHAR(45) NOT NULL,
  `user_type_value` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `knowledgehub`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knowledgehub`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `auth_key` VARCHAR(32) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `password_hash` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `password_reset_token` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `email` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `created_at` INT(11) NOT NULL,
  `updated_at` INT(11) NOT NULL,
  `role_id` INT(11) NOT NULL DEFAULT '10',
  `status_id` INT(11) NOT NULL DEFAULT '10',
  `user_type_id` INT(11) NOT NULL DEFAULT '10',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username` (`username` ASC),
  UNIQUE INDEX `email` (`email` ASC),
  UNIQUE INDEX `password_reset_token` (`password_reset_token` ASC),
  INDEX `fk_user_role1_idx` (`role_id` ASC),
  INDEX `fk_user_status1_idx` (`status_id` ASC),
  INDEX `fk_user_user_type1_idx` (`user_type_id` ASC),
  CONSTRAINT `fk_user_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `knowledgehub`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_status1`
    FOREIGN KEY (`status_id`)
    REFERENCES `knowledgehub`.`status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_user_type1`
    FOREIGN KEY (`user_type_id`)
    REFERENCES `knowledgehub`.`user_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `knowledgehub`.`provinsi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knowledgehub`.`provinsi` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `kode` INT(11) NULL DEFAULT NULL,
  `title` VARCHAR(45) NOT NULL,
  `created_date` DATETIME NOT NULL,
  `created_by` INT(11) NOT NULL,
  `updated_date` DATETIME NOT NULL,
  `updated_by` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `kode_UNIQUE` (`kode` ASC),
  INDEX `fk_provinsi_user1_idx` (`created_by` ASC),
  INDEX `fk_provinsi_user2_idx` (`updated_by` ASC),
  CONSTRAINT `fk_provinsi_user1`
    FOREIGN KEY (`created_by`)
    REFERENCES `knowledgehub`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_provinsi_user2`
    FOREIGN KEY (`updated_by`)
    REFERENCES `knowledgehub`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `knowledgehub`.`kabupaten`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knowledgehub`.`kabupaten` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `kode` INT(11) NULL DEFAULT NULL,
  `title` VARCHAR(45) NOT NULL,
  `provinsi_id` INT(11) NOT NULL,
  `created_date` DATETIME NOT NULL,
  `created_by` INT(11) NOT NULL,
  `updated_date` DATETIME NOT NULL,
  `updated_by` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `kode_UNIQUE` (`kode` ASC),
  INDEX `fk_kabupaten_provinsi1_idx` (`provinsi_id` ASC),
  INDEX `fk_kabupaten_user1_idx` (`created_by` ASC),
  INDEX `fk_kabupaten_user2_idx` (`updated_by` ASC),
  CONSTRAINT `fk_kabupaten_provinsi1`
    FOREIGN KEY (`provinsi_id`)
    REFERENCES `knowledgehub`.`provinsi` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_kabupaten_user1`
    FOREIGN KEY (`created_by`)
    REFERENCES `knowledgehub`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_kabupaten_user2`
    FOREIGN KEY (`updated_by`)
    REFERENCES `knowledgehub`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `knowledgehub`.`kecamatan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knowledgehub`.`kecamatan` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `kode` INT(11) NULL DEFAULT NULL,
  `title` VARCHAR(45) NOT NULL,
  `kabupaten_id` INT(11) NOT NULL,
  `provinsi_id` INT(11) NOT NULL,
  `created_date` DATETIME NOT NULL,
  `created_by` INT(11) NOT NULL,
  `updated_date` DATETIME NOT NULL,
  `updated_by` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `kode_UNIQUE` (`kode` ASC),
  INDEX `fk_kecamatan_kabupaten1_idx` (`kabupaten_id` ASC),
  INDEX `fk_kecamatan_provinsi1_idx` (`provinsi_id` ASC),
  INDEX `fk_kecamatan_user1_idx` (`created_by` ASC),
  INDEX `fk_kecamatan_user2_idx` (`updated_by` ASC),
  CONSTRAINT `fk_kecamatan_kabupaten1`
    FOREIGN KEY (`kabupaten_id`)
    REFERENCES `knowledgehub`.`kabupaten` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_kecamatan_provinsi1`
    FOREIGN KEY (`provinsi_id`)
    REFERENCES `knowledgehub`.`provinsi` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_kecamatan_user1`
    FOREIGN KEY (`created_by`)
    REFERENCES `knowledgehub`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_kecamatan_user2`
    FOREIGN KEY (`updated_by`)
    REFERENCES `knowledgehub`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `knowledgehub`.`type_media_sosial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knowledgehub`.`type_media_sosial` (
  `id` INT(11) NOT NULL,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  `description` MEDIUMTEXT NULL DEFAULT NULL,
  `icon` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `knowledgehub`.`member_organisasi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knowledgehub`.`member_organisasi` (
  `id` INT(11) NOT NULL,
  `user_id` INT(11) NOT NULL,
  `user_profile_id` INT(11) NOT NULL,
  `organisasi_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_member_organisasi_user_profile1_idx` (`user_profile_id` ASC),
  INDEX `fk_member_organisasi_user1_idx` (`user_id` ASC),
  INDEX `fk_member_organisasi_organisasi1_idx` (`organisasi_id` ASC),
  CONSTRAINT `fk_member_organisasi_organisasi1`
    FOREIGN KEY (`organisasi_id`)
    REFERENCES `knowledgehub`.`organisasi` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_member_organisasi_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `knowledgehub`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_member_organisasi_user_profile1`
    FOREIGN KEY (`user_profile_id`)
    REFERENCES `knowledgehub`.`user_profile` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `knowledgehub`.`mitra_organisasi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knowledgehub`.`mitra_organisasi` (
  `id` INT(11) NOT NULL,
  `organisasi_id` INT(11) NOT NULL,
  `nama_mitra` VARCHAR(255) NOT NULL,
  `deskripsi` MEDIUMTEXT NULL DEFAULT NULL,
  `alamat` VARCHAR(255) NULL DEFAULT NULL,
  `telphon` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `website` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_mitra_organisasi_organisasi1_idx` (`organisasi_id` ASC),
  CONSTRAINT `fk_mitra_organisasi_organisasi1`
    FOREIGN KEY (`organisasi_id`)
    REFERENCES `knowledgehub`.`organisasi` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `knowledgehub`.`pengalaman_organisasi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knowledgehub`.`pengalaman_organisasi` (
  `id` INT(11) NOT NULL,
  `organisasi_id` INT(11) NOT NULL,
  `tahun_mulai` YEAR(4) NOT NULL,
  `tahun_selesai` YEAR(4) NOT NULL,
  `nama_kegiatan` VARCHAR(255) NOT NULL,
  `lokasi_provinsi_id` INT(11) NULL DEFAULT NULL,
  `lokasi_kabupaten_id` INT(11) NULL DEFAULT NULL,
  `lokasi_kecamatan_id` INT(11) NULL DEFAULT NULL,
  `mitra_organisasi_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pengalaman_organisasi_organisasi1_idx` (`organisasi_id` ASC),
  INDEX `fk_pengalaman_organisasi_provinsi1_idx` (`lokasi_provinsi_id` ASC),
  INDEX `fk_pengalaman_organisasi_kabupaten1_idx` (`lokasi_kabupaten_id` ASC),
  INDEX `fk_pengalaman_organisasi_kecamatan1_idx` (`lokasi_kecamatan_id` ASC),
  INDEX `fk_pengalaman_organisasi_mitra_organisasi1_idx` (`mitra_organisasi_id` ASC),
  CONSTRAINT `fk_pengalaman_organisasi_kabupaten1`
    FOREIGN KEY (`lokasi_kabupaten_id`)
    REFERENCES `knowledgehub`.`kabupaten` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pengalaman_organisasi_kecamatan1`
    FOREIGN KEY (`lokasi_kecamatan_id`)
    REFERENCES `knowledgehub`.`kecamatan` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pengalaman_organisasi_mitra_organisasi1`
    FOREIGN KEY (`mitra_organisasi_id`)
    REFERENCES `knowledgehub`.`mitra_organisasi` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pengalaman_organisasi_organisasi1`
    FOREIGN KEY (`organisasi_id`)
    REFERENCES `knowledgehub`.`organisasi` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pengalaman_organisasi_provinsi1`
    FOREIGN KEY (`lokasi_provinsi_id`)
    REFERENCES `knowledgehub`.`provinsi` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `knowledgehub`.`kompetensi_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knowledgehub`.`kompetensi_category` (
  `id` INT(11) NOT NULL,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  `description` MEDIUMTEXT NULL DEFAULT NULL,
  `parrent_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_category_isue_category_isue1_idx` (`parrent_id` ASC),
  CONSTRAINT `fk_category_isue_category_isue1`
    FOREIGN KEY (`parrent_id`)
    REFERENCES `knowledgehub`.`kompetensi_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `knowledgehub`.`level_penilaian`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knowledgehub`.`level_penilaian` (
  `id` INT(11) NOT NULL,
  `value` TINYINT(2) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `knowledgehub`.`ranah_kompetensi_organisasi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knowledgehub`.`ranah_kompetensi_organisasi` (
  `id` INT(11) NOT NULL,
  `organisasi_id` INT(11) NOT NULL,
  `kompetensi_category_id` INT(11) NOT NULL,
  `user_profile_id` INT(11) NOT NULL,
  `level_penilaian_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ranah_kompetensi_organisasi_kompetensi_category1_idx` (`kompetensi_category_id` ASC),
  INDEX `fk_ranah_kompetensi_organisasi_user_profile1_idx` (`user_profile_id` ASC),
  INDEX `fk_ranah_kompetensi_organisasi_level_penilaian1_idx` (`level_penilaian_id` ASC),
  INDEX `fk_ranah_kompetensi_organisasi_organisasi1_idx` (`organisasi_id` ASC),
  CONSTRAINT `fk_ranah_kompetensi_organisasi_kompetensi_category1`
    FOREIGN KEY (`kompetensi_category_id`)
    REFERENCES `knowledgehub`.`kompetensi_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ranah_kompetensi_organisasi_level_penilaian1`
    FOREIGN KEY (`level_penilaian_id`)
    REFERENCES `knowledgehub`.`level_penilaian` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ranah_kompetensi_organisasi_organisasi1`
    FOREIGN KEY (`organisasi_id`)
    REFERENCES `knowledgehub`.`organisasi` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ranah_kompetensi_organisasi_user_profile1`
    FOREIGN KEY (`user_profile_id`)
    REFERENCES `knowledgehub`.`user_profile` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `knowledgehub`.`struktur_organisasi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knowledgehub`.`struktur_organisasi` (
  `id` INT(11) NOT NULL,
  `organisasi_id` INT(11) NOT NULL,
  `jabatan` VARCHAR(255) NULL DEFAULT NULL,
  `urutkan_jabatan` INT(4) NULL DEFAULT NULL,
  `description` MEDIUMTEXT NULL DEFAULT NULL,
  `parrent_id` INT(11) NOT NULL,
  `user_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_struktur_organisasi_organisasi1_idx` (`organisasi_id` ASC),
  INDEX `fk_struktur_organisasi_struktur_organisasi1_idx` (`parrent_id` ASC),
  INDEX `fk_struktur_organisasi_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_struktur_organisasi_organisasi1`
    FOREIGN KEY (`organisasi_id`)
    REFERENCES `knowledgehub`.`organisasi` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_struktur_organisasi_struktur_organisasi1`
    FOREIGN KEY (`parrent_id`)
    REFERENCES `knowledgehub`.`struktur_organisasi` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_struktur_organisasi_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `knowledgehub`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `knowledgehub`.`detail_profil_organisasi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knowledgehub`.`detail_profil_organisasi` (
  `id` INT(11) NOT NULL,
  `nama_pimpinan` VARCHAR(255) NOT NULL,
  `organisasi_id` INT(11) NOT NULL,
  `contact_organisasi_id` INT(11) NOT NULL,
  `visi` TEXT NULL DEFAULT NULL,
  `misi` TEXT NULL DEFAULT NULL,
  `tujuan` TEXT NULL DEFAULT NULL,
  `about` TEXT NULL DEFAULT NULL,
  `member_organisasi_id` INT(11) NOT NULL,
  `struktur_organisasi_id` INT(11) NOT NULL,
  `ranah_kompetensi_organisasi_id` INT(11) NOT NULL,
  `pengalaman_organisasi_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_detail_profil_organisasi_organisasi1_idx` (`organisasi_id` ASC),
  INDEX `fk_detail_profil_organisasi_member_organisasi1_idx` (`member_organisasi_id` ASC),
  INDEX `fk_detail_profil_organisasi_struktur_organisasi1_idx` (`struktur_organisasi_id` ASC),
  INDEX `fk_detail_profil_organisasi_ranah_kompetensi_organisasi1_idx` (`ranah_kompetensi_organisasi_id` ASC),
  INDEX `fk_detail_profil_organisasi_contact_organisasi1_idx` (`contact_organisasi_id` ASC),
  INDEX `fk_detail_profil_organisasi_pengalaman_organisasi1_idx` (`pengalaman_organisasi_id` ASC),
  CONSTRAINT `fk_detail_profil_organisasi_contact_organisasi1`
    FOREIGN KEY (`contact_organisasi_id`)
    REFERENCES `knowledgehub`.`contact_organisasi` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detail_profil_organisasi_member_organisasi1`
    FOREIGN KEY (`member_organisasi_id`)
    REFERENCES `knowledgehub`.`member_organisasi` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detail_profil_organisasi_organisasi1`
    FOREIGN KEY (`organisasi_id`)
    REFERENCES `knowledgehub`.`organisasi` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detail_profil_organisasi_pengalaman_organisasi1`
    FOREIGN KEY (`pengalaman_organisasi_id`)
    REFERENCES `knowledgehub`.`pengalaman_organisasi` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detail_profil_organisasi_ranah_kompetensi_organisasi1`
    FOREIGN KEY (`ranah_kompetensi_organisasi_id`)
    REFERENCES `knowledgehub`.`ranah_kompetensi_organisasi` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detail_profil_organisasi_struktur_organisasi1`
    FOREIGN KEY (`struktur_organisasi_id`)
    REFERENCES `knowledgehub`.`struktur_organisasi` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `knowledgehub`.`organisasi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knowledgehub`.`organisasi` (
  `id` INT(11) NOT NULL,
  `nama_organisasi` VARCHAR(255) NULL DEFAULT NULL,
  `singkatan` VARCHAR(45) NULL DEFAULT NULL,
  `logo` VARCHAR(45) NULL DEFAULT NULL,
  `tageline` VARCHAR(255) NULL DEFAULT NULL,
  `detail_profil_organisasi_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_organisasi_detail_profil_organisasi1_idx` (`detail_profil_organisasi_id` ASC),
  CONSTRAINT `fk_organisasi_detail_profil_organisasi1`
    FOREIGN KEY (`detail_profil_organisasi_id`)
    REFERENCES `knowledgehub`.`detail_profil_organisasi` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `knowledgehub`.`medsos_organisasi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knowledgehub`.`medsos_organisasi` (
  `id` INT(11) NOT NULL,
  `organisasi_id` INT(11) NOT NULL,
  `type_media_sosial_id` INT(11) NOT NULL,
  `url` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_medsos_organisasi_organisasi1_idx` (`organisasi_id` ASC),
  INDEX `fk_medsos_organisasi_media_sosial1_idx` (`type_media_sosial_id` ASC),
  CONSTRAINT `fk_medsos_organisasi_media_sosial1`
    FOREIGN KEY (`type_media_sosial_id`)
    REFERENCES `knowledgehub`.`type_media_sosial` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medsos_organisasi_organisasi1`
    FOREIGN KEY (`organisasi_id`)
    REFERENCES `knowledgehub`.`organisasi` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `knowledgehub`.`contact_organisasi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knowledgehub`.`contact_organisasi` (
  `id` INT(11) NOT NULL,
  `organisasi_id` INT(11) NOT NULL,
  `alamat` VARCHAR(255) NOT NULL,
  `provinsi_id` INT(11) NOT NULL,
  `kabupaten_id` INT(11) NOT NULL,
  `kecamatan_id` INT(11) NOT NULL,
  `kodepos` INT(11) NULL DEFAULT NULL,
  `telephone` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `website` VARCHAR(45) NULL DEFAULT NULL,
  `medsos_organisasi_id` INT(11) NOT NULL,
  `koordinat` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_contact_organisasi_organisasi1_idx` (`organisasi_id` ASC),
  INDEX `fk_contact_organisasi_provinsi1_idx` (`provinsi_id` ASC),
  INDEX `fk_contact_organisasi_kabupaten1_idx` (`kabupaten_id` ASC),
  INDEX `fk_contact_organisasi_kecamatan1_idx` (`kecamatan_id` ASC),
  INDEX `fk_contact_organisasi_medsos_organisasi1_idx` (`medsos_organisasi_id` ASC),
  CONSTRAINT `fk_contact_organisasi_kabupaten1`
    FOREIGN KEY (`kabupaten_id`)
    REFERENCES `knowledgehub`.`kabupaten` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contact_organisasi_kecamatan1`
    FOREIGN KEY (`kecamatan_id`)
    REFERENCES `knowledgehub`.`kecamatan` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contact_organisasi_medsos_organisasi1`
    FOREIGN KEY (`medsos_organisasi_id`)
    REFERENCES `knowledgehub`.`medsos_organisasi` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contact_organisasi_organisasi1`
    FOREIGN KEY (`organisasi_id`)
    REFERENCES `knowledgehub`.`organisasi` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contact_organisasi_provinsi1`
    FOREIGN KEY (`provinsi_id`)
    REFERENCES `knowledgehub`.`provinsi` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `knowledgehub`.`gender`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knowledgehub`.`gender` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `gender_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `knowledgehub`.`image_video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knowledgehub`.`image_video` (
  `id` INT(11) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `slug` VARCHAR(255) NOT NULL,
  `description` MEDIUMTEXT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `urlpath` VARCHAR(45) NOT NULL,
  `created_date` DATETIME NOT NULL,
  `created_by` INT(11) NOT NULL,
  `updated_date` DATETIME NOT NULL,
  `updated_by` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_image_user1_idx` (`created_by` ASC),
  INDEX `fk_image_user2_idx` (`updated_by` ASC),
  CONSTRAINT `fk_image_user1`
    FOREIGN KEY (`created_by`)
    REFERENCES `knowledgehub`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_image_user2`
    FOREIGN KEY (`updated_by`)
    REFERENCES `knowledgehub`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `knowledgehub`.`jenis_spesialisasi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knowledgehub`.`jenis_spesialisasi` (
  `id` INT(11) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `description` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `knowledgehub`.`jenjang_pendidikan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knowledgehub`.`jenjang_pendidikan` (
  `id` INT(11) NOT NULL,
  `jenjang` VARCHAR(45) NULL DEFAULT NULL,
  `deskripsi` MEDIUMTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `knowledgehub`.`migration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knowledgehub`.`migration` (
  `version` VARCHAR(180) NOT NULL,
  `apply_time` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`version`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `knowledgehub`.`pengalaman_kompetensi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knowledgehub`.`pengalaman_kompetensi` (
  `id` INT(11) NOT NULL,
  `user_id` INT(11) NOT NULL,
  `tahun` YEAR(4) NOT NULL,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  `description` MEDIUMTEXT NULL DEFAULT NULL,
  `lokasi` VARCHAR(255) NULL DEFAULT NULL,
  `durasi` VARCHAR(45) NULL DEFAULT NULL,
  `kompetensi_category_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pengalaman_kompetensi_user1_idx` (`user_id` ASC),
  INDEX `fk_pengalaman_kompetensi_kompetensi_category1_idx` (`kompetensi_category_id` ASC),
  CONSTRAINT `fk_pengalaman_kompetensi_kompetensi_category1`
    FOREIGN KEY (`kompetensi_category_id`)
    REFERENCES `knowledgehub`.`kompetensi_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pengalaman_kompetensi_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `knowledgehub`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `knowledgehub`.`post_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knowledgehub`.`post_category` (
  `id` INT(11) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `slug` VARCHAR(255) NULL DEFAULT NULL,
  `description` MEDIUMTEXT NOT NULL,
  `parrent_id` INT(11) NOT NULL,
  `show` TINYINT(2) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by` INT(11) NOT NULL,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_by` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_post_category_post_category_idx` (`parrent_id` ASC),
  INDEX `fk_post_category_user1_idx` (`created_by` ASC),
  INDEX `fk_post_category_user2_idx` (`updated_by` ASC),
  CONSTRAINT `fk_post_category_post_category`
    FOREIGN KEY (`parrent_id`)
    REFERENCES `knowledgehub`.`post_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_category_user1`
    FOREIGN KEY (`created_by`)
    REFERENCES `knowledgehub`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_category_user2`
    FOREIGN KEY (`updated_by`)
    REFERENCES `knowledgehub`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `knowledgehub`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knowledgehub`.`post` (
  `id` INT(11) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `slug` VARCHAR(255) NULL DEFAULT NULL,
  `post_category_id` INT(11) NOT NULL,
  `description` MEDIUMTEXT NOT NULL,
  `future_image` VARCHAR(255) NULL DEFAULT NULL,
  `content` TEXT NOT NULL,
  `tag` VARCHAR(255) NULL DEFAULT NULL,
  `show` INT(2) NOT NULL,
  `created_date` DATETIME NOT NULL,
  `created_by` INT(11) NOT NULL,
  `updated_date` DATETIME NOT NULL,
  `updated_by` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_post_post_category1_idx` (`post_category_id` ASC),
  INDEX `fk_post_user1_idx` (`created_by` ASC),
  INDEX `fk_post_user2_idx` (`updated_by` ASC),
  CONSTRAINT `fk_post_post_category1`
    FOREIGN KEY (`post_category_id`)
    REFERENCES `knowledgehub`.`post_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_user1`
    FOREIGN KEY (`created_by`)
    REFERENCES `knowledgehub`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_user2`
    FOREIGN KEY (`updated_by`)
    REFERENCES `knowledgehub`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `knowledgehub`.`profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knowledgehub`.`profile` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NOT NULL,
  `first_name` TEXT NULL DEFAULT NULL,
  `last_name` TEXT NULL DEFAULT NULL,
  `birthday` DATE NULL DEFAULT NULL,
  `gender_id` INT(11) NOT NULL,
  `created_at` VARCHAR(45) NULL DEFAULT NULL,
  `updated_at` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_profile_user1_idx` (`user_id` ASC),
  INDEX `fk_profile_gender2_idx` (`gender_id` ASC),
  CONSTRAINT `fk_profile_gender2`
    FOREIGN KEY (`gender_id`)
    REFERENCES `knowledgehub`.`gender` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_profile_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `knowledgehub`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `knowledgehub`.`setting`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knowledgehub`.`setting` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `key` VARCHAR(45) NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `created_date` DATETIME NOT NULL,
  `created_by` INT(11) NOT NULL,
  `updated_date` DATETIME NOT NULL,
  `updated_by` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_setting_user1_idx` (`created_by` ASC),
  INDEX `fk_setting_user2_idx` (`updated_by` ASC),
  CONSTRAINT `fk_setting_user1`
    FOREIGN KEY (`created_by`)
    REFERENCES `knowledgehub`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_setting_user2`
    FOREIGN KEY (`updated_by`)
    REFERENCES `knowledgehub`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `knowledgehub`.`slider_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knowledgehub`.`slider_category` (
  `id` INT(11) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `slug` VARCHAR(255) NULL DEFAULT NULL,
  `description` MEDIUMTEXT NOT NULL,
  `type` VARCHAR(45) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` INT(11) NOT NULL,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `updated_by` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_post_category_user1_idx` (`created_by` ASC),
  INDEX `fk_post_category_user2_idx` (`updated_by` ASC),
  CONSTRAINT `fk_post_category_user10`
    FOREIGN KEY (`created_by`)
    REFERENCES `knowledgehub`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_category_user20`
    FOREIGN KEY (`updated_by`)
    REFERENCES `knowledgehub`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `knowledgehub`.`slider_content`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knowledgehub`.`slider_content` (
  `id` INT(11) NOT NULL,
  `slider_id` INT(11) NOT NULL,
  `image_video_id` INT(11) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `description` MEDIUMTEXT NOT NULL,
  `show` TINYINT(2) NOT NULL,
  `urlpath` VARCHAR(255) NULL DEFAULT NULL,
  `created_date` DATETIME NULL DEFAULT NULL,
  `created_by` INT(11) NOT NULL,
  `updated_date` DATETIME NULL DEFAULT NULL,
  `updated_by` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_content_slider_slider1_idx` (`slider_id` ASC),
  INDEX `fk_slider_content_image_video1_idx` (`image_video_id` ASC),
  INDEX `fk_slider_content_user1_idx` (`created_by` ASC),
  INDEX `fk_slider_content_user2_idx` (`updated_by` ASC),
  CONSTRAINT `fk_content_slider_slider1`
    FOREIGN KEY (`slider_id`)
    REFERENCES `knowledgehub`.`slider` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_slider_content_image_video1`
    FOREIGN KEY (`image_video_id`)
    REFERENCES `knowledgehub`.`image_video` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_slider_content_user1`
    FOREIGN KEY (`created_by`)
    REFERENCES `knowledgehub`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_slider_content_user2`
    FOREIGN KEY (`updated_by`)
    REFERENCES `knowledgehub`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `knowledgehub`.`slider`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `knowledgehub`.`slider` (
  `id` INT(11) NOT NULL,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  `slider_category_id` INT(11) NOT NULL,
  `slider_content_id` INT(11) NOT NULL,
  `created_date` DATETIME NOT NULL,
  `updated_date` DATETIME NOT NULL,
  `created_by` INT(11) NOT NULL,
  `updated_by` INT(11) NOT NULL,
  `show` TINYINT(2) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_slider_slider_category1_idx` (`slider_category_id` ASC),
  INDEX `fk_slider_slider_content1_idx` (`slider_content_id` ASC),
  INDEX `fk_slider_user1_idx` (`created_by` ASC),
  INDEX `fk_slider_user2_idx` (`updated_by` ASC),
  CONSTRAINT `fk_slider_slider_category1`
    FOREIGN KEY (`slider_category_id`)
    REFERENCES `knowledgehub`.`slider_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_slider_slider_content1`
    FOREIGN KEY (`slider_content_id`)
    REFERENCES `knowledgehub`.`slider_content` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_slider_user1`
    FOREIGN KEY (`created_by`)
    REFERENCES `knowledgehub`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_slider_user2`
    FOREIGN KEY (`updated_by`)
    REFERENCES `knowledgehub`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
